# Generated by Django 2.2.7 on 2020-01-14 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_delete_comment'),
    ]

    operations = [

    ]
