from django.urls import path
from pams_system.views.levels import *
from pams_system.views.maps import *
from pams_system.views.kpis import *

# ap_name = 'pams'

urlpatterns = [
    # the url paths for maps categories
    path('maplist/<maptype>/', MapListIndex.as_view(), name='mapListIndex'),
    path('create/', MapListCreateView.as_view(), name='create_map_list'),
    path('update/<int:pk>', MapListUpdateView.as_view(), name='update_map_list'),
    path('read/<int:pk>', MapListReadView.as_view(), name='read_map_list'),
    path('delete/<int:pk>', MapListDeleteView.as_view(), name='delete_map_list'),
    path('maps/', MapTypeIndex.as_view(), name='mapTypeIndex'),
    path('createmaptype/', MapTypeCreateView.as_view(), name='create_maptype'),
    path('updatemaptype/<int:pk>', MaptypeUpdateView.as_view(), name='update_maptype'),
    path('readmaptype/<int:pk>', MapTypeReadView.as_view(), name='read_maptype'),
    path('deletemaptype/<int:pk>', MapTypeDeleteView.as_view(), name='delete_maptype'),
    # the url paths for the level and data structures
    path('levels/<maplist>/', LevelIndex.as_view(), name='levelIndex'),
    path('createlevellist/', LevelListCreateView.as_view(), name='create_levellist'),
    path('updatelevel/<int:pk>', LevelUpdateView.as_view(), name='update_level'),
    path('readlevel/<int:pk>', LevelReadView.as_view(), name='read_level'),
    path('deletelevel/<int:pk>', LevelDeleteView.as_view(), name='delete_level'),
    path('levelStructure/<maplist>/', LevelStructureIndex.as_view(), name='levelStructureIndex'),
    path('DataStructure/<int:maplist_pk>/<str:strategic_objective>/<int:tree_pk>/', DataStructure.as_view(),
         name='dataStructureIndex'),
    path('createlevelstructure/', LevelStructureCreateView.as_view(), name='create_level_structure'),
    path('create_kpi_structure/', KpiStructureCreateView.as_view(), name='create_kpitype_structure'),
    path('updatelevelstructure/<int:pk>', LevelStructureUpdateView.as_view(), name='update_level_structure'),
    path('readlevelstructure/<int:pk>', LevelStructureReadView.as_view(), name='read_level_structure'),
    path('deletelevelstructure/<int:pk>', LevelStructureDeleteView.as_view(), name='delete_level_structure'),
    # the url paths for the kpis, its values, dates, weights etc...
    path('kpitype/<int:data>/', KpiTypeIndex.as_view(), name='kpiTypeIndex'),
    path('createkpitype/', KpiTypeCreateView.as_view(), name='create_kpi_type'),
    path('updatekpitype/<int:pk>', KpiTypeUpdateView.as_view(), name='update_kpi_type'),
    path('readkpitype/<int:pk>', KpiTypeReadView.as_view(), name='read_kpi_type'),
    path('deletekpitype/<int:pk>', KpiTypeDeleteView.as_view(), name='delete_kpi_type'),
    path('kpiuser/', KpiUserIndex.as_view(), name='kpiUserIndex'),
    path('createkpiuser/', KpiUserCreateView.as_view(), name='create_kpi_user'),
    path('assign_kpi_user/', KpiAssignUserView.as_view(), name='assign_kpi_user'),
    path('updatekpiuser/<int:pk>', KpiUserUpdateView.as_view(), name='update_kpi_user'),
    path('update_kpi_user_group/<int:pk>/', KpiUserGroupUpdateView.as_view(), name='update_kpi_group_user'),
    path('readkpiuser/<int:pk>/', KpiUserReadView.as_view(), name='read_kpi_user'),
    path('read_kpi_user/', KpiStatsSummary, name='stats_summary'),
    path('deletekpiuser/<int:pk>', KpiUserDeleteView.as_view(), name='delete_kpi_user'),
    path('kpigroup/', KpiGroupIndex.as_view(), name='kpiGroupIndex'),
    path('createkpigroup/', KpiGroupCreateView.as_view(), name='create_kpi_group'),
    path('assign_group/', KpiAssignGroupView.as_view(), name='assign_group'),
    path('updatekpigroup/<int:pk>', KpiGroupUpdateView.as_view(), name='update_kpi_group'),
    path('kpi_group_membership/', KpiMembershipView.as_view(), name='membership_kpi_group'),
    path('kpi_group_membership_update/<int:pk>/', KpiMembershipUpdateView.as_view(), name='membership_kpi_groupset'),
    path('remove_member/<int:individual>/<int:group>', remove_member, name='remove_member'),
    path('readkpigroup/<int:pk>', KpiGroupReadView.as_view(), name='read_kpi_group'),
    path('deletekpigroup/<int:pk>', KpiGroupDeleteView.as_view(), name='delete_kpi_group'),
    path('kpivalue/', KpiValueIndex.as_view(), name='kpiValueIndex'),
    path('createkpivalue/', KpiValueCreateView.as_view(), name='create_kpi_value'),
    path('create_group_value/', KpiGroupValueCreateView.as_view(), name='create_group_value'),
    path('updatekpivalue/<int:pk>', KpiValueUpdateView.as_view(), name='update_kpi_value'),
    path('readkpivalue/<int:pk>', KpiValueReadView.as_view(), name='read_kpi_value'),
    path('deletekpivalue/<int:pk>', KpiValueDeleteView.as_view(), name='delete_kpi_value'),
    path('kpidate/', KpiDatesIndex.as_view(), name='kpiDatesIndex'),
    path('createkpidate/', KpiDatesCreateView.as_view(), name='create_kpi_date'),
    path('updatekpidate/<int:pk>', KpiDatesUpdateView.as_view(), name='update_kpi_date'),
    path('readkpidate/<int:pk>', KpiDatesReadView.as_view(), name='read_kpi_date'),
    path('deletekpidate/<int:pk>', KpiDatesDeleteView.as_view(), name='delete_kpi_date'),
    path('kpiweight/', KpiWeightsIndex.as_view(), name='kpiWeightsIndex'),
    path('createkpiweight/', KpiWeightsCreateView.as_view(), name='create_kpi_weight'),
    path('updatekpiweight/<int:pk>', KpiWeightsUpdateView.as_view(), name='update_kpi_weight'),
    path('readkpiweight/<int:pk>', KpiWeightsReadView.as_view(), name='read_kpi_weight'),
    path('deletekpiweight/<int:pk>', KpiWeightsDeleteView.as_view(), name='delete_kpi_weight'),
    path('ajax/specific-maplist/', specific_maplist, name='ajax_specific_maplist_data'),
    path('ajax/get_kpisets/', get_kpisets, name='ajax_get_kpisets'),
    path('ajax/specific-kpis/', specific_kpi, name='ajax_specific_kpi'),
    path('add_weights/', add_weights, name='add_kpi_weights'),
    path('print_view/', print_view, name='print_documents'),
    path('populate_forms/<pk>',populate_forms,name="populate_forms"),
    path('seding_results_to_email/', sending_results, name='sending_results'),
    path('get_previous',get_previous_data_str,name='get_previous_parentset'),
    # path('get_previous_kpi',get_previous_data_kpi,name='get_previous_kpi_parentset'),
]
#
