# Generated by Django 2.2.7 on 2020-01-10 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_auto_20190410_2136'),
    ]

    operations = [

    ]
