#!/bin/bash 
  
NAME="setup"                                 					# Name of the application 
DJANGODIR=/srv/www/html/performance_system         # Django project directory 
SOCKFILE=127.0.0.1:8000   # we will communicte using this unix socket 
USER=actserv                                       				# the user to run as 
GROUP=actserv                                    				# the group to run as 
NUM_WORKERS=3                                    				# how many worker processes should Gunicorn spawn 
DJANGO_SETTINGS_MODULE=setup.settings            				# which settings file should Django use
DJANGO_WSGI_MODULE=setup.wsgi                    				# WSGI module name
  
echo "Starting $NAME as `whoami`" 
  
# Activate the virtual environment 
cd $DJANGODIR
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE 
export PYTHONPATH=$DJANGODIR:$PYTHONPATH 
  
# Create the run directory if it doesn't exist 
# RUNDIR=$(dirname $SOCKFILE) 
# test -d $RUNDIR || mkdir -p $RUNDIR 
  
# Start your Django Unicorn 
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon) 
pipenv shell
exec gunicorn ${DJANGO_WSGI_MODULE}:application \ 
 --name $NAME \ 
 --workers $NUM_WORKERS \ 
 --user=$USER --group=$GROUP \ 
 --bind=$SOCKFILE \ 
 --log-level=debug \ 
 --log-file=- 



