# Generated by Django 2.2.7 on 2020-01-13 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_delete_comment'),
    ]

    operations = [

    ]
