# Generated by Django 2.2.7 on 2020-01-14 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_delete_comment'),
    ]

    operations = [

    ]
