# Generated by Django 2.2.7 on 2020-01-15 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0008_delete_comment'),
    ]

    operations = [
    ]
