# Generated by Django 2.2.7 on 2020-01-15 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0009_delete_comment'),
    ]

    operations = [

    ]
