# Generated by Django 2.2.7 on 2019-12-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='client_code',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='task',
            name='client_name',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
    ]
