# Generated by Django 2.2.7 on 2020-01-20 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_auto_20191217_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='project',
            new_name='title',
        ),
    ]
