# Generated by Django 2.2.7 on 2020-01-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pams_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpimain',
            name='ok',
            field=models.IntegerField(null=True),
        ),
    ]
