# Generated by Django 2.2.7 on 2020-01-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pams_system', '0005_auto_20200128_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpiindividual',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='button to toggle participant deleted and undelete', verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='kpiindividual',
            name='is_suspended',
            field=models.BooleanField(default=False, help_text='button to toggle partcipant block and unblock', verbose_name='Is Blocked'),
        ),
        migrations.AddField(
            model_name='kpiindividual',
            name='status',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=255),
        ),
    ]
