# Generated by Django 2.2.7 on 2020-01-31 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pams_system', '0006_auto_20200130_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpigroups',
            name='ind',
        ),
        migrations.AlterField(
            model_name='kpigroups',
            name='group',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='kpiindividual',
            name='status',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=255, verbose_name='Suspend Participant'),
        ),
        migrations.CreateModel(
            name='KpiMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pams_system.KpiGroups')),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pams_system.KpiIndividual')),
            ],
        ),
        migrations.AddField(
            model_name='kpigroups',
            name='members',
            field=models.ManyToManyField(through='pams_system.KpiMembership', to='pams_system.KpiIndividual'),
        ),
    ]
