# Generated by Django 2.2.7 on 2020-01-31 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pams_system', '0008_auto_20200131_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpimembership',
            name='date_joined',
            field=models.DateField(null=True),
        ),
    ]
