# Generated by Django 2.2.7 on 2020-01-31 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pams_system', '0009_auto_20200131_0623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kpimembership',
            old_name='date_joined',
            new_name='effective_date_joined',
        ),
    ]
