# Generated by Django 2.2.7 on 2020-01-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pams_system', '0010_auto_20200131_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpigroups',
            name='group',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
