# Generated by Django 2.2.7 on 2020-02-03 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pams_system', '0011_auto_20200131_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpivalue',
            name='kpitype',
        ),
    ]
