# Generated by Django 2.2.7 on 2020-02-03 07:47

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pams_system', '0013_kpivalues'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpivalues',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_groupset', to='pams_system.KpiGroups'),
        ),
        migrations.AlterField(
            model_name='kpivalues',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pams_system.KpiValues', verbose_name='Categories'),
        ),
    ]
