# Generated by Django 2.2.7 on 2020-03-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pams_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputdata',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
