# Generated by Django 3.0.4 on 2020-04-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pams_system', '0006_auto_20200403_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputdata',
            name='previous_datastructure',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
