# Generated by Django 3.0.4 on 2020-03-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pams_system', '0004_auto_20200317_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapSet',
            fields=[
                ('status', models.CharField(choices=[('U', 'Unlocked'), ('L', 'Locked'), ('E', 'Edited'), ('D', 'Deleted'), ('N', 'Null')], default='N', max_length=255)),
                ('state', models.CharField(choices=[('U', 'Unlocked'), ('L', 'Locked'), ('E', 'Edited'), ('D', 'Deleted'), ('N', 'Null')], default='N', max_length=255)),
                ('maplist_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_data', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_data', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
