# Generated by Django 3.0.5 on 2020-04-03 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pams_system', '0005_mapset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpistats',
            name='individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pams_system.KpiParticipants'),
        ),
    ]
