# Generated by Django 3.0.4 on 2020-05-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pams_system', '0008_auto_20200424_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputdata',
            name='is_datastructure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inputdata',
            name='is_kpi',
            field=models.BooleanField(default=False),
        ),
    ]
